apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnectS2I
metadata:
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
  name: my-connect-s2i-cluster
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap:9093'
  version: 2.8.0
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  replicas: 1
  jvmOptions:
    javaSystemProperties:
      - name: java.security.disableSystemPropertiesFile
        value: 'true'
  config:
    group.id: my-connect-cluster
    offset.storage.topic: my-connect-cluster-offsets
    config.storage.topic: my-connect-cluster-configs
    status.storage.topic: my-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
