apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    resources:
      limits:
        cpu: '1'
        memory: 8Gi
      requests:
        cpu: 0.4
        memory: 8Gi
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external1
        port: 9094
        type: route
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: persistent-claim
      size: 15Gi
      class: ocs-storagecluster-cephfs
  zookeeper:
    replicas: 3
    resources:
      requests:
        cpu: 0.2
        memory: 4Gi
      limits:
        cpu: 1
        memory: 4Gi
    storage:
      type: persistent-claim
      size: 3Gi
      class: ocs-storagecluster-cephfs
  entityOperator:
    topicOperator: {}
    userOperator: {}
